baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Netspective Strategy & Planning"
theme = "netspective"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true

[params]
  themeVariant = "netspective"
  themeVariantSidebarMastheadLogo = "/images/branding/main-masthead-logo-for-dark-bg.png"
  description = "Strategy and Planning"
  author = "Mathieu Cornic"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

